=== PratikPatil4008/WT/Ex-14-xml_internal,external_DTD/personInfo.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT personinfo (person+)>
<!ELEMENT person (name, profession, age, city)>
<!ELEMENT name (firstname, lastname)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT profession (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ATTLIST person pid ID #REQUIRED>

=== PratikPatil4008/WT/Ex-14-xml_internal,external_DTD/ExternalDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personinfo SYSTEM "personinfo.dtd"><!-- DTD - Document Type Defination -->
<personinfo>
    <person pid="P1">
        <name>
            <firstname>Pranav</firstname>
            <lastname>Bhokare</lastname>
        </name>
        <profession>Student</profession>
        <age>21</age>
        <city>Ichalkaranji</city>
    </person>
    <person pid="P2">
        <name>
            <firstname>ABC</firstname>
            <lastname>XYZ</lastname>
        </name>
        <profession>Teacher</profession>
        <age>42</age>
        <city>Kolhapur</city>
    </person>
</personinfo>
